sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
language: node_js
node_js:
  - '9'
script:
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
